

export const metadata = {
    title: "Admin page",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    return (
        <>
        <span>Admin Navbar</span>
            {children}
        </>
    );
}
